apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: webapp
    process: web
  name: webapp-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp
        process: web
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
          envFrom:
            - configMapRef:
                name: webapp
          image: docker.io/oleholinyk/rubyapp:latest
          imagePullPolicy: IfNotPresent
          name: webapp-web
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /health_check/healthcheck
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
          resources:
            limits:
              cpu: "200m"
              memory: "128Mi"
            requests:
              cpu: "150m"
              memory: "128Mi"
      restartPolicy: Always