apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: webapp
  template:
    metadata:
      labels:
        name: webapp
    spec:
      containers:
        - name: webapp
          image: oleholinyk/rubyapp:latest
          ports:
            - containerPort: 3000
