apiVersion: batch/v1
kind: Job
metadata:
  name: webapp-service-migrate
  labels:
    app.kubernetes.io/name: webapp-service-migrate
spec:
#  backoffLimit: 4  # Number of retries before considering the Job failed
#  activeDeadlineSeconds: 600  # Maximum time (in seconds) the Job can run
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp-service-migrate
    spec:
      containers:
        - command:
            - rails
            - db:migrate
          envFrom:
            - configMapRef:
                name: webapp-service
            - configMapRef:
                name: postgresql
          image: docker.io/oleholinyk/rubyapp:latest
          imagePullPolicy: IfNotPresent
          name: main
#          resources:
#            requests:
#              cpu: "100m"   # Minimum resources requested
#              memory: "128Mi"
#            limits:
#              cpu: "200m"   # Maximum resources allowed
#              memory: "256Mi"
      restartPolicy: Never