apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: webapp-service
    process: web
  name: webapp-service-web
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: webapp-service
      process: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: webapp-service
        process: web
    spec:
      containers:
        - env:
            - name: PORT
              value: "80"
#          envFrom:
#            - configMapRef:
#                name: webapp-service
#            - configMapRef:
#                name: postgresql
          image: docker.io/oleholinyk/rubyapp:latest
          imagePullPolicy: IfNotPresent
          name: webapp-service-web
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "250m"
              memory: "128Mi"
      restartPolicy: Always